// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: api/proto/agent/sbom.proto

package agent

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SBOMSource indicates how the SBOM was produced (Finding #8.4)
type SBOMSource int32

const (
	SBOMSource_SBOM_SOURCE_UNKNOWN               SBOMSource = 0
	SBOMSource_SBOM_SOURCE_PARSERS               SBOMSource = 1 // Package managers (dpkg, apk, rpm, npm, etc.)
	SBOMSource_SBOM_SOURCE_DISTROLLESS_HEURISTIC SBOMSource = 2 // Synthetic/heuristic for distroless/system images
	SBOMSource_SBOM_SOURCE_LABEL_METADATA        SBOMSource = 3 // From OCI labels / image metadata only
)

// Enum value maps for SBOMSource.
var (
	SBOMSource_name = map[int32]string{
		0: "SBOM_SOURCE_UNKNOWN",
		1: "SBOM_SOURCE_PARSERS",
		2: "SBOM_SOURCE_DISTROLLESS_HEURISTIC",
		3: "SBOM_SOURCE_LABEL_METADATA",
	}
	SBOMSource_value = map[string]int32{
		"SBOM_SOURCE_UNKNOWN":               0,
		"SBOM_SOURCE_PARSERS":               1,
		"SBOM_SOURCE_DISTROLLESS_HEURISTIC": 2,
		"SBOM_SOURCE_LABEL_METADATA":        3,
	}
)

func (x SBOMSource) Enum() *SBOMSource {
	p := new(SBOMSource)
	*p = x
	return p
}

func (x SBOMSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SBOMSource) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_agent_sbom_proto_enumTypes[0].Descriptor()
}

func (SBOMSource) Type() protoreflect.EnumType {
	return &file_api_proto_agent_sbom_proto_enumTypes[0]
}

func (x SBOMSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SBOMSource.Descriptor instead.
func (SBOMSource) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_agent_sbom_proto_rawDescGZIP(), []int{0}
}

// Confidence level for SBOM or component (Finding #8.4)
type Confidence int32

const (
	Confidence_CONFIDENCE_UNKNOWN Confidence = 0
	Confidence_CONFIDENCE_LOW     Confidence = 1
	Confidence_CONFIDENCE_MEDIUM  Confidence = 2
	Confidence_CONFIDENCE_HIGH    Confidence = 3
)

// Enum value maps for Confidence.
var (
	Confidence_name = map[int32]string{
		0: "CONFIDENCE_UNKNOWN",
		1: "CONFIDENCE_LOW",
		2: "CONFIDENCE_MEDIUM",
		3: "CONFIDENCE_HIGH",
	}
	Confidence_value = map[string]int32{
		"CONFIDENCE_UNKNOWN": 0,
		"CONFIDENCE_LOW":     1,
		"CONFIDENCE_MEDIUM":  2,
		"CONFIDENCE_HIGH":    3,
	}
)

func (x Confidence) Enum() *Confidence {
	p := new(Confidence)
	*p = x
	return p
}

func (x Confidence) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Confidence) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_agent_sbom_proto_enumTypes[1].Descriptor()
}

func (Confidence) Type() protoreflect.EnumType {
	return &file_api_proto_agent_sbom_proto_enumTypes[1]
}

func (x Confidence) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Confidence.Descriptor instead.
func (Confidence) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_agent_sbom_proto_rawDescGZIP(), []int{1}
}

// PackageType enum
type PackageType int32

const (
	PackageType_PACKAGE_TYPE_UNKNOWN PackageType = 0
	PackageType_PACKAGE_TYPE_DEB     PackageType = 1  // Debian/Ubuntu
	PackageType_PACKAGE_TYPE_RPM     PackageType = 2  // Red Hat/CentOS
	PackageType_PACKAGE_TYPE_APK     PackageType = 3  // Alpine
	PackageType_PACKAGE_TYPE_NPM     PackageType = 4  // Node.js
	PackageType_PACKAGE_TYPE_PYPI    PackageType = 5  // Python
	PackageType_PACKAGE_TYPE_GEM     PackageType = 6  // Ruby
	PackageType_PACKAGE_TYPE_GO_MOD  PackageType = 7  // Go modules
	PackageType_PACKAGE_TYPE_MAVEN   PackageType = 8  // Java Maven
	PackageType_PACKAGE_TYPE_CARGO   PackageType = 9  // Rust
	PackageType_PACKAGE_TYPE_GENERIC PackageType = 10 // Distroless/system heuristic (pkg:generic/...)
)

// Enum value maps for PackageType.
var (
	PackageType_name = map[int32]string{
		0:  "PACKAGE_TYPE_UNKNOWN",
		1:  "PACKAGE_TYPE_DEB",
		2:  "PACKAGE_TYPE_RPM",
		3:  "PACKAGE_TYPE_APK",
		4:  "PACKAGE_TYPE_NPM",
		5:  "PACKAGE_TYPE_PYPI",
		6:  "PACKAGE_TYPE_GEM",
		7:  "PACKAGE_TYPE_GO_MOD",
		8:  "PACKAGE_TYPE_MAVEN",
		9:  "PACKAGE_TYPE_CARGO",
		10: "PACKAGE_TYPE_GENERIC",
	}
	PackageType_value = map[string]int32{
		"PACKAGE_TYPE_UNKNOWN": 0,
		"PACKAGE_TYPE_DEB":     1,
		"PACKAGE_TYPE_RPM":     2,
		"PACKAGE_TYPE_APK":     3,
		"PACKAGE_TYPE_NPM":     4,
		"PACKAGE_TYPE_PYPI":    5,
		"PACKAGE_TYPE_GEM":     6,
		"PACKAGE_TYPE_GO_MOD":  7,
		"PACKAGE_TYPE_MAVEN":   8,
		"PACKAGE_TYPE_CARGO":   9,
		"PACKAGE_TYPE_GENERIC": 10,
	}
)

func (x PackageType) Enum() *PackageType {
	p := new(PackageType)
	*p = x
	return p
}

func (x PackageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PackageType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_agent_sbom_proto_enumTypes[2].Descriptor()
}

func (PackageType) Type() protoreflect.EnumType {
	return &file_api_proto_agent_sbom_proto_enumTypes[2]
}

func (x PackageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PackageType.Descriptor instead.
func (PackageType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_agent_sbom_proto_rawDescGZIP(), []int{2}
}

// SBOMFinding represents SBOM data extracted by Agent
type SBOMFinding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Schema version for evolution
	SchemaVersion int32 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// Pod identity (required)
	PodUid        string `protobuf:"bytes,2,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	PodName       string `protobuf:"bytes,3,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Namespace     string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ContainerName string `protobuf:"bytes,5,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	// Image info (required)
	ImageName   string `protobuf:"bytes,6,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	ImageDigest string `protobuf:"bytes,7,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"` // sha256:abc123...
	ImageTag    string `protobuf:"bytes,8,opt,name=image_tag,json=imageTag,proto3" json:"image_tag,omitempty"`
	// Operating System (optional)
	OsInfo *OSInfo `protobuf:"bytes,9,opt,name=os_info,json=osInfo,proto3" json:"os_info,omitempty"`
	// Packages (required)
	Packages []*Package `protobuf:"bytes,10,rep,name=packages,proto3" json:"packages,omitempty"`
	// Metadata (required)
	GeneratedAt *timestamp.Timestamp `protobuf:"bytes,11,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	AgentId     string               `protobuf:"bytes,12,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	NodeId      string               `protobuf:"bytes,13,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Additional context (optional)
	Labels      map[string]string `protobuf:"bytes,14,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations map[string]string `protobuf:"bytes,15,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// SBOM provenance (Finding #8.4) – Core uses for CVE matching policy (e.g. heuristic vs package-manager SBOMs)
	SbomSource    SBOMSource `protobuf:"varint,16,opt,name=sbom_source,json=sbomSource,proto3,enum=fortuna.agent.v1.SBOMSource" json:"sbom_source,omitempty"`
	Confidence    Confidence `protobuf:"varint,17,opt,name=confidence,proto3,enum=fortuna.agent.v1.Confidence" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SBOMFinding) Reset() {
	*x = SBOMFinding{}
	mi := &file_api_proto_agent_sbom_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SBOMFinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SBOMFinding) ProtoMessage() {}

func (x *SBOMFinding) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_sbom_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SBOMFinding.ProtoReflect.Descriptor instead.
func (*SBOMFinding) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_sbom_proto_rawDescGZIP(), []int{0}
}

func (x *SBOMFinding) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *SBOMFinding) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *SBOMFinding) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *SBOMFinding) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SBOMFinding) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *SBOMFinding) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *SBOMFinding) GetImageDigest() string {
	if x != nil {
		return x.ImageDigest
	}
	return ""
}

func (x *SBOMFinding) GetImageTag() string {
	if x != nil {
		return x.ImageTag
	}
	return ""
}

func (x *SBOMFinding) GetOsInfo() *OSInfo {
	if x != nil {
		return x.OsInfo
	}
	return nil
}

func (x *SBOMFinding) GetPackages() []*Package {
	if x != nil {
		return x.Packages
	}
	return nil
}

func (x *SBOMFinding) GetGeneratedAt() *timestamp.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *SBOMFinding) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SBOMFinding) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SBOMFinding) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *SBOMFinding) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *SBOMFinding) GetSbomSource() SBOMSource {
	if x != nil {
		return x.SbomSource
	}
	return SBOMSource_SBOM_SOURCE_UNKNOWN
}

func (x *SBOMFinding) GetConfidence() Confidence {
	if x != nil {
		return x.Confidence
	}
	return Confidence_CONFIDENCE_UNKNOWN
}

// OSInfo describes the container OS
type OSInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                 // e.g., "debian", "alpine", "ubuntu"
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`           // e.g., "11", "3.18", "22.04"
	Variant       string                 `protobuf:"bytes,3,opt,name=variant,proto3" json:"variant,omitempty"`           // e.g., "slim", "musl"
	Architecture  string                 `protobuf:"bytes,4,opt,name=architecture,proto3" json:"architecture,omitempty"` // e.g., "amd64", "arm64"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OSInfo) Reset() {
	*x = OSInfo{}
	mi := &file_api_proto_agent_sbom_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OSInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSInfo) ProtoMessage() {}

func (x *OSInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_sbom_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSInfo.ProtoReflect.Descriptor instead.
func (*OSInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_sbom_proto_rawDescGZIP(), []int{1}
}

func (x *OSInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OSInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *OSInfo) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

func (x *OSInfo) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

// Package represents a software package
type Package struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Name         string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                    // e.g., "nginx"
	Version      string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                              // e.g., "1.21.6"
	Type         PackageType            `protobuf:"varint,3,opt,name=type,proto3,enum=fortuna.agent.v1.PackageType" json:"type,omitempty"` // Enum of package types
	Architecture string                 `protobuf:"bytes,4,opt,name=architecture,proto3" json:"architecture,omitempty"`                    // e.g., "amd64", "all"
	Licenses     []string               `protobuf:"bytes,5,rep,name=licenses,proto3" json:"licenses,omitempty"`
	Source       string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"` // e.g., source package name (Debian source pkg)
	// Optional metadata
	Description string `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Homepage    string `protobuf:"bytes,8,opt,name=homepage,proto3" json:"homepage,omitempty"`
	Maintainer  string `protobuf:"bytes,9,opt,name=maintainer,proto3" json:"maintainer,omitempty"`
	// Canonical PURL (Finding #8.2) – e.g. pkg:generic/coredns@1.11.0 for distroless
	Purl          string `protobuf:"bytes,10,opt,name=purl,proto3" json:"purl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Package) Reset() {
	*x = Package{}
	mi := &file_api_proto_agent_sbom_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_sbom_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_sbom_proto_rawDescGZIP(), []int{2}
}

func (x *Package) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Package) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Package) GetType() PackageType {
	if x != nil {
		return x.Type
	}
	return PackageType_PACKAGE_TYPE_UNKNOWN
}

func (x *Package) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *Package) GetLicenses() []string {
	if x != nil {
		return x.Licenses
	}
	return nil
}

func (x *Package) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Package) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Package) GetHomepage() string {
	if x != nil {
		return x.Homepage
	}
	return ""
}

func (x *Package) GetMaintainer() string {
	if x != nil {
		return x.Maintainer
	}
	return ""
}

func (x *Package) GetPurl() string {
	if x != nil {
		return x.Purl
	}
	return ""
}

// SBOMFindingResponse returned by Core
type SBOMFindingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SbomId        string                 `protobuf:"bytes,3,opt,name=sbom_id,json=sbomId,proto3" json:"sbom_id,omitempty"` // Used to reference in CVEFinding
	ReceivedAt    *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SBOMFindingResponse) Reset() {
	*x = SBOMFindingResponse{}
	mi := &file_api_proto_agent_sbom_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SBOMFindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SBOMFindingResponse) ProtoMessage() {}

func (x *SBOMFindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_agent_sbom_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SBOMFindingResponse.ProtoReflect.Descriptor instead.
func (*SBOMFindingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_agent_sbom_proto_rawDescGZIP(), []int{3}
}

func (x *SBOMFindingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SBOMFindingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SBOMFindingResponse) GetSbomId() string {
	if x != nil {
		return x.SbomId
	}
	return ""
}

func (x *SBOMFindingResponse) GetReceivedAt() *timestamp.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

var File_api_proto_agent_sbom_proto protoreflect.FileDescriptor

const file_api_proto_agent_sbom_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/proto/agent/sbom.proto\x12\x10fortuna.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf6\x06\n" +
	"\vSBOMFinding\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\x05R\rschemaVersion\x12\x17\n" +
	"\apod_uid\x18\x02 \x01(\tR\x06podUid\x12\x19\n" +
	"\bpod_name\x18\x03 \x01(\tR\apodName\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12%\n" +
	"\x0econtainer_name\x18\x05 \x01(\tR\rcontainerName\x12\x1d\n" +
	"\n" +
	"image_name\x18\x06 \x01(\tR\timageName\x12!\n" +
	"\fimage_digest\x18\a \x01(\tR\vimageDigest\x12\x1b\n" +
	"\timage_tag\x18\b \x01(\tR\bimageTag\x121\n" +
	"\aos_info\x18\t \x01(\v2\x18.fortuna.agent.v1.OSInfoR\x06osInfo\x125\n" +
	"\bpackages\x18\n" +
	" \x03(\v2\x19.fortuna.agent.v1.PackageR\bpackages\x12=\n" +
	"\fgenerated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x12\x19\n" +
	"\bagent_id\x18\f \x01(\tR\aagentId\x12\x17\n" +
	"\anode_id\x18\r \x01(\tR\x06nodeId\x12A\n" +
	"\x06labels\x18\x0e \x03(\v2).fortuna.agent.v1.SBOMFinding.LabelsEntryR\x06labels\x12P\n" +
	"\vannotations\x18\x0f \x03(\v2..fortuna.agent.v1.SBOMFinding.AnnotationsEntryR\vannotations\x12=\n" +
	"\vsbom_source\x18\x10 \x01(\x0e2\x1c.fortuna.agent.v1.SBOMSourceR\n" +
	"sbomSource\x12<\n" +
	"\n" +
	"confidence\x18\x11 \x01(\x0e2\x1c.fortuna.agent.v1.ConfidenceR\n" +
	"confidence\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"t\n" +
	"\x06OSInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x18\n" +
	"\avariant\x18\x03 \x01(\tR\avariant\x12\"\n" +
	"\farchitecture\x18\x04 \x01(\tR\farchitecture\"\xb4\x02\n" +
	"\aPackage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x121\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1d.fortuna.agent.v1.PackageTypeR\x04type\x12\"\n" +
	"\farchitecture\x18\x04 \x01(\tR\farchitecture\x12\x1a\n" +
	"\blicenses\x18\x05 \x03(\tR\blicenses\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x1a\n" +
	"\bhomepage\x18\b \x01(\tR\bhomepage\x12\x1e\n" +
	"\n" +
	"maintainer\x18\t \x01(\tR\n" +
	"maintainer\x12\x12\n" +
	"\x04purl\x18\n" +
	" \x01(\tR\x04purl\"\x9f\x01\n" +
	"\x13SBOMFindingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\asbom_id\x18\x03 \x01(\tR\x06sbomId\x12;\n" +
	"\vreceived_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt*\x85\x01\n" +
	"\n" +
	"SBOMSource\x12\x17\n" +
	"\x13SBOM_SOURCE_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13SBOM_SOURCE_PARSERS\x10\x01\x12%\n" +
	"!SBOM_SOURCE_DISTROLLESS_HEURISTIC\x10\x02\x12\x1e\n" +
	"\x1aSBOM_SOURCE_LABEL_METADATA\x10\x03*d\n" +
	"\n" +
	"Confidence\x12\x16\n" +
	"\x12CONFIDENCE_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eCONFIDENCE_LOW\x10\x01\x12\x15\n" +
	"\x11CONFIDENCE_MEDIUM\x10\x02\x12\x13\n" +
	"\x0fCONFIDENCE_HIGH\x10\x03*\x8f\x02\n" +
	"\vPackageType\x12\x18\n" +
	"\x14PACKAGE_TYPE_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10PACKAGE_TYPE_DEB\x10\x01\x12\x14\n" +
	"\x10PACKAGE_TYPE_RPM\x10\x02\x12\x14\n" +
	"\x10PACKAGE_TYPE_APK\x10\x03\x12\x14\n" +
	"\x10PACKAGE_TYPE_NPM\x10\x04\x12\x15\n" +
	"\x11PACKAGE_TYPE_PYPI\x10\x05\x12\x14\n" +
	"\x10PACKAGE_TYPE_GEM\x10\x06\x12\x17\n" +
	"\x13PACKAGE_TYPE_GO_MOD\x10\a\x12\x16\n" +
	"\x12PACKAGE_TYPE_MAVEN\x10\b\x12\x16\n" +
	"\x12PACKAGE_TYPE_CARGO\x10\t\x12\x18\n" +
	"\x14PACKAGE_TYPE_GENERIC\x10\n" +
	"B$Z\"github.com/fortuna/api/proto/agentb\x06proto3"

var (
	file_api_proto_agent_sbom_proto_rawDescOnce sync.Once
	file_api_proto_agent_sbom_proto_rawDescData []byte
)

func file_api_proto_agent_sbom_proto_rawDescGZIP() []byte {
	file_api_proto_agent_sbom_proto_rawDescOnce.Do(func() {
		file_api_proto_agent_sbom_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_agent_sbom_proto_rawDesc), len(file_api_proto_agent_sbom_proto_rawDesc)))
	})
	return file_api_proto_agent_sbom_proto_rawDescData
}

var file_api_proto_agent_sbom_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_api_proto_agent_sbom_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_agent_sbom_proto_goTypes = []any{
	(SBOMSource)(0),             // 0: fortuna.agent.v1.SBOMSource
	(Confidence)(0),             // 1: fortuna.agent.v1.Confidence
	(PackageType)(0),            // 2: fortuna.agent.v1.PackageType
	(*SBOMFinding)(nil),         // 3: fortuna.agent.v1.SBOMFinding
	(*OSInfo)(nil),              // 4: fortuna.agent.v1.OSInfo
	(*Package)(nil),             // 5: fortuna.agent.v1.Package
	(*SBOMFindingResponse)(nil), // 6: fortuna.agent.v1.SBOMFindingResponse
	nil,                         // 7: fortuna.agent.v1.SBOMFinding.LabelsEntry
	nil,                         // 8: fortuna.agent.v1.SBOMFinding.AnnotationsEntry
	(*timestamp.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_api_proto_agent_sbom_proto_depIdxs = []int32{
	4, // 0: fortuna.agent.v1.SBOMFinding.os_info:type_name -> fortuna.agent.v1.OSInfo
	5, // 1: fortuna.agent.v1.SBOMFinding.packages:type_name -> fortuna.agent.v1.Package
	9, // 2: fortuna.agent.v1.SBOMFinding.generated_at:type_name -> google.protobuf.Timestamp
	7, // 3: fortuna.agent.v1.SBOMFinding.labels:type_name -> fortuna.agent.v1.SBOMFinding.LabelsEntry
	8, // 4: fortuna.agent.v1.SBOMFinding.annotations:type_name -> fortuna.agent.v1.SBOMFinding.AnnotationsEntry
	0, // 5: fortuna.agent.v1.SBOMFinding.sbom_source:type_name -> fortuna.agent.v1.SBOMSource
	1, // 6: fortuna.agent.v1.SBOMFinding.confidence:type_name -> fortuna.agent.v1.Confidence
	2, // 7: fortuna.agent.v1.Package.type:type_name -> fortuna.agent.v1.PackageType
	9, // 8: fortuna.agent.v1.SBOMFindingResponse.received_at:type_name -> google.protobuf.Timestamp
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_api_proto_agent_sbom_proto_init() }
func file_api_proto_agent_sbom_proto_init() {
	if File_api_proto_agent_sbom_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_agent_sbom_proto_rawDesc), len(file_api_proto_agent_sbom_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_agent_sbom_proto_goTypes,
		DependencyIndexes: file_api_proto_agent_sbom_proto_depIdxs,
		EnumInfos:         file_api_proto_agent_sbom_proto_enumTypes,
		MessageInfos:      file_api_proto_agent_sbom_proto_msgTypes,
	}.Build()
	File_api_proto_agent_sbom_proto = out.File
	file_api_proto_agent_sbom_proto_goTypes = nil
	file_api_proto_agent_sbom_proto_depIdxs = nil
}
