export const GRAPH_THEME = {
  surface: 'rgb(var(--color-base))',
  surfaceDeep: 'rgb(var(--color-base))',
  text: 'rgb(var(--color-text))',
  muted: 'rgb(var(--color-muted))',
  muted2: 'rgb(var(--color-muted-2))',
  border: 'rgb(var(--color-border))',
  critical: 'rgb(var(--color-critical))',
  high: 'rgb(var(--color-high))',
  medium: 'rgb(var(--color-medium))',
  low: 'rgb(var(--color-low))',
  success: 'rgb(var(--color-success))',
  warning: 'rgb(var(--color-warning))',
  info: 'rgb(var(--color-info))',
  brand: 'rgb(var(--color-brand))',
  brandStrong: 'rgb(var(--color-brand-strong))',
  teal: 'rgb(var(--color-success))',
  cyan: 'rgb(var(--color-info))',
  violet: 'rgb(var(--color-brand))',
  indigo: 'rgb(var(--color-low))',
  pink: 'rgb(var(--color-brand))',
  rose: 'rgb(var(--color-critical))',
  white: 'rgb(var(--color-text))',
} as const;

export const GRAPH_EDGE_COLORS: Record<string, string> = {
  PATH_ENTRY: '#67e8f9',
  SERVICE_ACCOUNT_ACCESS: '#a78bfa',
  RBAC_BINDING: '#f59e0b',
  GRANTS_ROLE: '#f472b6',
  NETWORK_REACH: '#22c55e',
  NETWORK_REACH_SOFT: '#94a3b8',
  CONTAINER_ESCAPE: '#ef4444',
  ESC_HOSTPATH_NODE: '#ef4444',
  ESC_HOSTPID: '#f87171',
  HOST_ACCESS: '#fb7185',
  LATERAL_MOVE: '#38bdf8',
  HAS_ATTACK_STEP: '#84cc16',
  CAN_STEAL_CREDENTIALS: '#eab308',
};

export const ATTACK_NODE_COLORS: Record<string, { fill: string; stroke: string }> = {
  path_entry: { fill: '#0e7490', stroke: '#67e8f9' },
  pod: { fill: '#2563eb', stroke: '#93c5fd' },
  service_account: { fill: '#7c3aed', stroke: '#c4b5fd' },
  serviceaccount: { fill: '#7c3aed', stroke: '#c4b5fd' },
  role_binding: { fill: '#d97706', stroke: '#fcd34d' },
  rolebinding: { fill: '#d97706', stroke: '#fcd34d' },
  cluster_role_binding: { fill: '#ea580c', stroke: '#fed7aa' },
  clusterrolebinding: { fill: '#ea580c', stroke: '#fed7aa' },
  role: { fill: '#0891b2', stroke: '#67e8f9' },
  cluster_role: { fill: '#db2777', stroke: '#f9a8d4' },
  clusterrole: { fill: '#db2777', stroke: '#f9a8d4' },
  capability: { fill: '#059669', stroke: '#86efac' },
  attack_step: { fill: '#65a30d', stroke: '#bef264' },
  node: { fill: '#dc2626', stroke: '#fecaca' },
  secret: { fill: '#ca8a04', stroke: '#fde68a' },
};
