apiVersion: v1
kind: Namespace
metadata:
  name: fortuna
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull
  namespace: fortuna
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "<github-user>",
          "password": "<github-token-with-read-packages>",
          "auth": "<base64-github-user-colon-token>"
        }
      }
    }
