apiVersion: v1
kind: ServiceAccount
metadata:
  name: fortuna-core
  namespace: fortuna
imagePullSecrets:
  - name: ghcr-pull
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fortuna-agent
  namespace: fortuna
imagePullSecrets:
  - name: ghcr-pull
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: fortuna
imagePullSecrets:
  - name: ghcr-pull
