apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../infrastructure/postgresql-with-age.yaml
  - ../infrastructure/nats.yaml
  - ../fortuna-rbac.yaml
  - ../fortuna-core-deployment.yaml
  - ../fortuna-agent-daemonset.yaml
  - ../dashboard-nginx-configmap.yaml
  - ../dashboard-deployment.yaml
images:
  - name: ghcr.io/shino-337/fortuna-community/fortuna-core
    newTag: v1.0.0
  - name: ghcr.io/shino-337/fortuna-community/fortuna-agent
    newTag: v1.0.0
  - name: ghcr.io/shino-337/fortuna-community/fortuna-dashboard
    newTag: v1.0.0
