/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './design-system/**/*.{ts,tsx}',
    './pages/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
    './store/**/*.{ts,tsx}',
    './hooks/**/*.{ts,tsx}',
    './constants/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      fontSize: {
        'page-title': ['1.5rem', { lineHeight: '2rem', fontWeight: '700' }],
        'section-title': ['1.125rem', { lineHeight: '1.5rem', fontWeight: '600' }],
        prose: ['1rem', { lineHeight: '1.625rem', fontWeight: '400' }],
        'card-title': ['1rem', { lineHeight: '1.5rem', fontWeight: '600' }],
        body: ['0.875rem', { lineHeight: '1.375rem', fontWeight: '400' }],
        caption: ['0.75rem', { lineHeight: '1rem', fontWeight: '500' }],
        /** ~11px secondary UI */
        meta: ['0.6875rem', { lineHeight: '1rem', fontWeight: '400' }],
        /** ~10px dense labels */
        micro: ['0.625rem', { lineHeight: '0.875rem', fontWeight: '500' }],
        /** ~9px, mono chips and graph legend */
        nano: ['0.5625rem', { lineHeight: '0.75rem', fontWeight: '500' }],
        /** Muted secondary copy (use with text-muted-2, not theme color key `muted`) */
        metric: ['1.375rem', { lineHeight: '1.75rem', fontWeight: '700' }],
        'metric-lg': ['1.75rem', { lineHeight: '2rem', fontWeight: '700' }],
        'lead-muted': ['0.75rem', { lineHeight: '1rem', fontWeight: '400' }],
      },
      fontFamily: {
        sans: [
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'sans-serif',
        ],
      },
      zIndex: {
        overlay: '40',
        dropdown: '50',
        popover: '60',
        modal: '80',
        toast: '90',
        skip: '100',
      },
      colors: {
        base: 'rgb(var(--color-base) / <alpha-value>)',
        surface: 'rgb(var(--color-surface) / <alpha-value>)',
        'surface-2': 'rgb(var(--color-surface-2) / <alpha-value>)',
        border: 'rgb(var(--color-border) / <alpha-value>)',
        text: 'rgb(var(--color-text) / <alpha-value>)',
        muted: 'rgb(var(--color-muted) / <alpha-value>)',
        'muted-2': 'rgb(var(--color-muted-2) / <alpha-value>)',
        brand: 'rgb(var(--color-brand) / <alpha-value>)',
        'brand-strong': 'rgb(var(--color-brand-strong) / <alpha-value>)',
        critical: 'rgb(var(--color-critical) / <alpha-value>)',
        high: 'rgb(var(--color-high) / <alpha-value>)',
        medium: 'rgb(var(--color-medium) / <alpha-value>)',
        low: 'rgb(var(--color-low) / <alpha-value>)',
        success: 'rgb(var(--color-success) / <alpha-value>)',
        warning: 'rgb(var(--color-warning) / <alpha-value>)',
        info: 'rgb(var(--color-info) / <alpha-value>)',
        error: 'rgb(var(--color-critical) / <alpha-value>)',
        /** Interactive variants for hover/focus states — use sparingly for affordances. */
        'error-hover': 'rgb(var(--color-critical) / 0.65)',
        'error-focus': 'rgb(var(--color-critical) / 0.9)',
        'error-foreground': 'rgb(var(--color-critical) / 0.88)',
        'error-background': 'rgb(var(--color-critical) / 0.14)',
        'error-border': 'rgb(var(--color-critical) / 0.45)',
        'error-muted': 'rgb(var(--color-critical) / 0.26)',
        'error-muted-foreground': 'rgb(var(--color-critical) / 0.65)',
        'error-ring': 'rgb(var(--color-critical) / 0.55)',
        'info-hover': 'rgb(var(--color-info) / 0.65)',
        'info-focus': 'rgb(var(--color-info) / 0.9)',
        'info-foreground': 'rgb(var(--color-info) / 0.88)',
        'info-background': 'rgb(var(--color-info) / 0.14)',
        'info-border': 'rgb(var(--color-info) / 0.45)',
        'info-muted': 'rgb(var(--color-info) / 0.26)',
        'info-muted-foreground': 'rgb(var(--color-info) / 0.65)',
        'info-ring': 'rgb(var(--color-info) / 0.55)',
        'success-hover': 'rgb(var(--color-success) / 0.65)',
        'success-focus': 'rgb(var(--color-success) / 0.9)',
        'success-foreground': 'rgb(var(--color-success) / 0.88)',
        'success-background': 'rgb(var(--color-success) / 0.14)',
        'success-border': 'rgb(var(--color-success) / 0.45)',
        'success-muted': 'rgb(var(--color-success) / 0.26)',
        'success-muted-foreground': 'rgb(var(--color-success) / 0.65)',
        'success-ring': 'rgb(var(--color-success) / 0.55)',
        'warning-hover': 'rgb(var(--color-warning) / 0.65)',
        'warning-focus': 'rgb(var(--color-warning) / 0.9)',
        'warning-foreground': 'rgb(var(--color-warning) / 0.88)',
        'warning-background': 'rgb(var(--color-warning) / 0.14)',
        'warning-border': 'rgb(var(--color-warning) / 0.45)',
        'warning-muted': 'rgb(var(--color-warning) / 0.26)',
        'warning-muted-foreground': 'rgb(var(--color-warning) / 0.65)',
        'warning-ring': 'rgb(var(--color-warning) / 0.55)',
      },
    },
  },
  plugins: [],
};
