apiVersion: v1
kind: Service
metadata:
  name: ksam-core
  namespace: fortuna
  labels:
    app: fortuna-core
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: grpc
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: fortuna-core

