// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/agent/cve.proto

package agent

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CVEFinding represents CVE vulnerabilities found in a container
type CVEFinding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Schema version for compatibility
	SchemaVersion int32 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	// Pod identification
	PodUid        string `protobuf:"bytes,2,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	PodName       string `protobuf:"bytes,3,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Namespace     string `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ContainerName string `protobuf:"bytes,5,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	// Image identification
	ImageName   string `protobuf:"bytes,6,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	ImageDigest string `protobuf:"bytes,7,opt,name=image_digest,json=imageDigest,proto3" json:"image_digest,omitempty"`
	ImageTag    string `protobuf:"bytes,8,opt,name=image_tag,json=imageTag,proto3" json:"image_tag,omitempty"`
	// CVE matches
	Matches []*CVEMatch `protobuf:"bytes,9,rep,name=matches,proto3" json:"matches,omitempty"`
	// Metadata
	ScannedAt *timestamp.Timestamp `protobuf:"bytes,10,opt,name=scanned_at,json=scannedAt,proto3" json:"scanned_at,omitempty"`
	AgentId   string               `protobuf:"bytes,11,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	NodeId    string               `protobuf:"bytes,12,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Summary
	TotalMatches  int32 `protobuf:"varint,13,opt,name=total_matches,json=totalMatches,proto3" json:"total_matches,omitempty"`
	CriticalCount int32 `protobuf:"varint,14,opt,name=critical_count,json=criticalCount,proto3" json:"critical_count,omitempty"`
	HighCount     int32 `protobuf:"varint,15,opt,name=high_count,json=highCount,proto3" json:"high_count,omitempty"`
	MediumCount   int32 `protobuf:"varint,16,opt,name=medium_count,json=mediumCount,proto3" json:"medium_count,omitempty"`
	LowCount      int32 `protobuf:"varint,17,opt,name=low_count,json=lowCount,proto3" json:"low_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CVEFinding) Reset() {
	*x = CVEFinding{}
	mi := &file_proto_agent_cve_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CVEFinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CVEFinding) ProtoMessage() {}

func (x *CVEFinding) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_cve_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CVEFinding.ProtoReflect.Descriptor instead.
func (*CVEFinding) Descriptor() ([]byte, []int) {
	return file_proto_agent_cve_proto_rawDescGZIP(), []int{0}
}

func (x *CVEFinding) GetSchemaVersion() int32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *CVEFinding) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *CVEFinding) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *CVEFinding) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CVEFinding) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *CVEFinding) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *CVEFinding) GetImageDigest() string {
	if x != nil {
		return x.ImageDigest
	}
	return ""
}

func (x *CVEFinding) GetImageTag() string {
	if x != nil {
		return x.ImageTag
	}
	return ""
}

func (x *CVEFinding) GetMatches() []*CVEMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

func (x *CVEFinding) GetScannedAt() *timestamp.Timestamp {
	if x != nil {
		return x.ScannedAt
	}
	return nil
}

func (x *CVEFinding) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CVEFinding) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CVEFinding) GetTotalMatches() int32 {
	if x != nil {
		return x.TotalMatches
	}
	return 0
}

func (x *CVEFinding) GetCriticalCount() int32 {
	if x != nil {
		return x.CriticalCount
	}
	return 0
}

func (x *CVEFinding) GetHighCount() int32 {
	if x != nil {
		return x.HighCount
	}
	return 0
}

func (x *CVEFinding) GetMediumCount() int32 {
	if x != nil {
		return x.MediumCount
	}
	return 0
}

func (x *CVEFinding) GetLowCount() int32 {
	if x != nil {
		return x.LowCount
	}
	return 0
}

// CVEMatch represents a single CVE match
type CVEMatch struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CveId          string                 `protobuf:"bytes,1,opt,name=cve_id,json=cveId,proto3" json:"cve_id,omitempty"`                            // e.g., CVE-2024-1234
	PackageName    string                 `protobuf:"bytes,2,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`          // e.g., openssl
	PackageVersion string                 `protobuf:"bytes,3,opt,name=package_version,json=packageVersion,proto3" json:"package_version,omitempty"` // e.g., 1.1.1k
	Purl           string                 `protobuf:"bytes,4,opt,name=purl,proto3" json:"purl,omitempty"`                                           // Package URL
	Severity       string                 `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"`                                   // CRITICAL, HIGH, MEDIUM, LOW
	CvssScore      float64                `protobuf:"fixed64,6,opt,name=cvss_score,json=cvssScore,proto3" json:"cvss_score,omitempty"`              // 0-10
	Description    string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`                             // CVE description
	FixedIn        string                 `protobuf:"bytes,8,opt,name=fixed_in,json=fixedIn,proto3" json:"fixed_in,omitempty"`                      // Version with fix
	MatchedBy      string                 `protobuf:"bytes,9,opt,name=matched_by,json=matchedBy,proto3" json:"matched_by,omitempty"`                // Version range that matched
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CVEMatch) Reset() {
	*x = CVEMatch{}
	mi := &file_proto_agent_cve_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CVEMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CVEMatch) ProtoMessage() {}

func (x *CVEMatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_cve_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CVEMatch.ProtoReflect.Descriptor instead.
func (*CVEMatch) Descriptor() ([]byte, []int) {
	return file_proto_agent_cve_proto_rawDescGZIP(), []int{1}
}

func (x *CVEMatch) GetCveId() string {
	if x != nil {
		return x.CveId
	}
	return ""
}

func (x *CVEMatch) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *CVEMatch) GetPackageVersion() string {
	if x != nil {
		return x.PackageVersion
	}
	return ""
}

func (x *CVEMatch) GetPurl() string {
	if x != nil {
		return x.Purl
	}
	return ""
}

func (x *CVEMatch) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *CVEMatch) GetCvssScore() float64 {
	if x != nil {
		return x.CvssScore
	}
	return 0
}

func (x *CVEMatch) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CVEMatch) GetFixedIn() string {
	if x != nil {
		return x.FixedIn
	}
	return ""
}

func (x *CVEMatch) GetMatchedBy() string {
	if x != nil {
		return x.MatchedBy
	}
	return ""
}

// CVEFindingResponse is returned after receiving CVE findings
type CVEFindingResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	InsightsCreated string                 `protobuf:"bytes,3,opt,name=insights_created,json=insightsCreated,proto3" json:"insights_created,omitempty"` // Number of insights created
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CVEFindingResponse) Reset() {
	*x = CVEFindingResponse{}
	mi := &file_proto_agent_cve_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CVEFindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CVEFindingResponse) ProtoMessage() {}

func (x *CVEFindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_cve_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CVEFindingResponse.ProtoReflect.Descriptor instead.
func (*CVEFindingResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_cve_proto_rawDescGZIP(), []int{2}
}

func (x *CVEFindingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CVEFindingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CVEFindingResponse) GetInsightsCreated() string {
	if x != nil {
		return x.InsightsCreated
	}
	return ""
}

var File_proto_agent_cve_proto protoreflect.FileDescriptor

const file_proto_agent_cve_proto_rawDesc = "" +
	"\n" +
	"\x15proto/agent/cve.proto\x12\x10fortuna.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdb\x04\n" +
	"\n" +
	"CVEFinding\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\x05R\rschemaVersion\x12\x17\n" +
	"\apod_uid\x18\x02 \x01(\tR\x06podUid\x12\x19\n" +
	"\bpod_name\x18\x03 \x01(\tR\apodName\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12%\n" +
	"\x0econtainer_name\x18\x05 \x01(\tR\rcontainerName\x12\x1d\n" +
	"\n" +
	"image_name\x18\x06 \x01(\tR\timageName\x12!\n" +
	"\fimage_digest\x18\a \x01(\tR\vimageDigest\x12\x1b\n" +
	"\timage_tag\x18\b \x01(\tR\bimageTag\x124\n" +
	"\amatches\x18\t \x03(\v2\x1a.fortuna.agent.v1.CVEMatchR\amatches\x129\n" +
	"\n" +
	"scanned_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tscannedAt\x12\x19\n" +
	"\bagent_id\x18\v \x01(\tR\aagentId\x12\x17\n" +
	"\anode_id\x18\f \x01(\tR\x06nodeId\x12#\n" +
	"\rtotal_matches\x18\r \x01(\x05R\ftotalMatches\x12%\n" +
	"\x0ecritical_count\x18\x0e \x01(\x05R\rcriticalCount\x12\x1d\n" +
	"\n" +
	"high_count\x18\x0f \x01(\x05R\thighCount\x12!\n" +
	"\fmedium_count\x18\x10 \x01(\x05R\vmediumCount\x12\x1b\n" +
	"\tlow_count\x18\x11 \x01(\x05R\blowCount\"\x98\x02\n" +
	"\bCVEMatch\x12\x15\n" +
	"\x06cve_id\x18\x01 \x01(\tR\x05cveId\x12!\n" +
	"\fpackage_name\x18\x02 \x01(\tR\vpackageName\x12'\n" +
	"\x0fpackage_version\x18\x03 \x01(\tR\x0epackageVersion\x12\x12\n" +
	"\x04purl\x18\x04 \x01(\tR\x04purl\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\x12\x1d\n" +
	"\n" +
	"cvss_score\x18\x06 \x01(\x01R\tcvssScore\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x19\n" +
	"\bfixed_in\x18\b \x01(\tR\afixedIn\x12\x1d\n" +
	"\n" +
	"matched_by\x18\t \x01(\tR\tmatchedBy\"s\n" +
	"\x12CVEFindingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x10insights_created\x18\x03 \x01(\tR\x0finsightsCreatedB$Z\"github.com/fortuna/api/proto/agentb\x06proto3"

var (
	file_proto_agent_cve_proto_rawDescOnce sync.Once
	file_proto_agent_cve_proto_rawDescData []byte
)

func file_proto_agent_cve_proto_rawDescGZIP() []byte {
	file_proto_agent_cve_proto_rawDescOnce.Do(func() {
		file_proto_agent_cve_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_cve_proto_rawDesc), len(file_proto_agent_cve_proto_rawDesc)))
	})
	return file_proto_agent_cve_proto_rawDescData
}

var file_proto_agent_cve_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_agent_cve_proto_goTypes = []any{
	(*CVEFinding)(nil),          // 0: fortuna.agent.v1.CVEFinding
	(*CVEMatch)(nil),            // 1: fortuna.agent.v1.CVEMatch
	(*CVEFindingResponse)(nil),  // 2: fortuna.agent.v1.CVEFindingResponse
	(*timestamp.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_proto_agent_cve_proto_depIdxs = []int32{
	1, // 0: fortuna.agent.v1.CVEFinding.matches:type_name -> fortuna.agent.v1.CVEMatch
	3, // 1: fortuna.agent.v1.CVEFinding.scanned_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_agent_cve_proto_init() }
func file_proto_agent_cve_proto_init() {
	if File_proto_agent_cve_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_cve_proto_rawDesc), len(file_proto_agent_cve_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_agent_cve_proto_goTypes,
		DependencyIndexes: file_proto_agent_cve_proto_depIdxs,
		MessageInfos:      file_proto_agent_cve_proto_msgTypes,
	}.Build()
	File_proto_agent_cve_proto = out.File
	file_proto_agent_cve_proto_goTypes = nil
	file_proto_agent_cve_proto_depIdxs = nil
}
