// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: proto/agent/service.proto

package agent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_RegisterAgent_FullMethodName         = "/fortuna.agent.v1.AgentService/RegisterAgent"
	AgentService_Heartbeat_FullMethodName             = "/fortuna.agent.v1.AgentService/Heartbeat"
	AgentService_SendSBOMFinding_FullMethodName       = "/fortuna.agent.v1.AgentService/SendSBOMFinding"
	AgentService_BatchSendSBOMFindings_FullMethodName = "/fortuna.agent.v1.AgentService/BatchSendSBOMFindings"
	AgentService_SendCVEFinding_FullMethodName        = "/fortuna.agent.v1.AgentService/SendCVEFinding"
	AgentService_SendCombinedFinding_FullMethodName   = "/fortuna.agent.v1.AgentService/SendCombinedFinding"
	AgentService_Ping_FullMethodName                  = "/fortuna.agent.v1.AgentService/Ping"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService defines the gRPC service for Agent-Core communication
type AgentServiceClient interface {
	// RegisterAgent registers an agent with the core
	RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error)
	// Heartbeat sends periodic health status
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// SendSBOMFinding sends a single SBOM finding (deprecated - use SendCombinedFinding)
	SendSBOMFinding(ctx context.Context, in *SBOMFinding, opts ...grpc.CallOption) (*SBOMFindingResponse, error)
	// BatchSendSBOMFindings sends multiple SBOM findings (deprecated)
	BatchSendSBOMFindings(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SBOMFinding, BatchSBOMFindingResponse], error)
	// SendCVEFinding sends CVE findings for a container
	SendCVEFinding(ctx context.Context, in *CVEFinding, opts ...grpc.CallOption) (*CVEFindingResponse, error)
	// SendCombinedFinding sends both SBOM and CVE findings together
	SendCombinedFinding(ctx context.Context, in *CombinedFinding, opts ...grpc.CallOption) (*CombinedFindingResponse, error)
	// Ping for health checking
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterAgentResponse)
	err := c.cc.Invoke(ctx, AgentService_RegisterAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, AgentService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SendSBOMFinding(ctx context.Context, in *SBOMFinding, opts ...grpc.CallOption) (*SBOMFindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SBOMFindingResponse)
	err := c.cc.Invoke(ctx, AgentService_SendSBOMFinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) BatchSendSBOMFindings(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SBOMFinding, BatchSBOMFindingResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_BatchSendSBOMFindings_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SBOMFinding, BatchSBOMFindingResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_BatchSendSBOMFindingsClient = grpc.ClientStreamingClient[SBOMFinding, BatchSBOMFindingResponse]

func (c *agentServiceClient) SendCVEFinding(ctx context.Context, in *CVEFinding, opts ...grpc.CallOption) (*CVEFindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CVEFindingResponse)
	err := c.cc.Invoke(ctx, AgentService_SendCVEFinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SendCombinedFinding(ctx context.Context, in *CombinedFinding, opts ...grpc.CallOption) (*CombinedFindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CombinedFindingResponse)
	err := c.cc.Invoke(ctx, AgentService_SendCombinedFinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, AgentService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService defines the gRPC service for Agent-Core communication
type AgentServiceServer interface {
	// RegisterAgent registers an agent with the core
	RegisterAgent(context.Context, *RegisterAgentRequest) (*RegisterAgentResponse, error)
	// Heartbeat sends periodic health status
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// SendSBOMFinding sends a single SBOM finding (deprecated - use SendCombinedFinding)
	SendSBOMFinding(context.Context, *SBOMFinding) (*SBOMFindingResponse, error)
	// BatchSendSBOMFindings sends multiple SBOM findings (deprecated)
	BatchSendSBOMFindings(grpc.ClientStreamingServer[SBOMFinding, BatchSBOMFindingResponse]) error
	// SendCVEFinding sends CVE findings for a container
	SendCVEFinding(context.Context, *CVEFinding) (*CVEFindingResponse, error)
	// SendCombinedFinding sends both SBOM and CVE findings together
	SendCombinedFinding(context.Context, *CombinedFinding) (*CombinedFindingResponse, error)
	// Ping for health checking
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) RegisterAgent(context.Context, *RegisterAgentRequest) (*RegisterAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (UnimplementedAgentServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedAgentServiceServer) SendSBOMFinding(context.Context, *SBOMFinding) (*SBOMFindingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendSBOMFinding not implemented")
}
func (UnimplementedAgentServiceServer) BatchSendSBOMFindings(grpc.ClientStreamingServer[SBOMFinding, BatchSBOMFindingResponse]) error {
	return status.Error(codes.Unimplemented, "method BatchSendSBOMFindings not implemented")
}
func (UnimplementedAgentServiceServer) SendCVEFinding(context.Context, *CVEFinding) (*CVEFindingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendCVEFinding not implemented")
}
func (UnimplementedAgentServiceServer) SendCombinedFinding(context.Context, *CombinedFinding) (*CombinedFindingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendCombinedFinding not implemented")
}
func (UnimplementedAgentServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_RegisterAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).RegisterAgent(ctx, req.(*RegisterAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SendSBOMFinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SBOMFinding)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SendSBOMFinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_SendSBOMFinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SendSBOMFinding(ctx, req.(*SBOMFinding))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_BatchSendSBOMFindings_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).BatchSendSBOMFindings(&grpc.GenericServerStream[SBOMFinding, BatchSBOMFindingResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_BatchSendSBOMFindingsServer = grpc.ClientStreamingServer[SBOMFinding, BatchSBOMFindingResponse]

func _AgentService_SendCVEFinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CVEFinding)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SendCVEFinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_SendCVEFinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SendCVEFinding(ctx, req.(*CVEFinding))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SendCombinedFinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CombinedFinding)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SendCombinedFinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_SendCombinedFinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SendCombinedFinding(ctx, req.(*CombinedFinding))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fortuna.agent.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAgent",
			Handler:    _AgentService_RegisterAgent_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _AgentService_Heartbeat_Handler,
		},
		{
			MethodName: "SendSBOMFinding",
			Handler:    _AgentService_SendSBOMFinding_Handler,
		},
		{
			MethodName: "SendCVEFinding",
			Handler:    _AgentService_SendCVEFinding_Handler,
		},
		{
			MethodName: "SendCombinedFinding",
			Handler:    _AgentService_SendCombinedFinding_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _AgentService_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BatchSendSBOMFindings",
			Handler:       _AgentService_BatchSendSBOMFindings_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/agent/service.proto",
}
