// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: service.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterAgentRequest contains agent registration info
type RegisterAgentRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	AgentId      string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname     string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	NodeName     string                 `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Version      string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Capabilities []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Cluster ID from agent discovery (kube-system UID hash or env CLUSTER_ID). Core uses this as the real cluster id when set.
	ClusterId     string `protobuf:"bytes,6,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterAgentRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterAgentRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *RegisterAgentRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterAgentRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterAgentRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

// RegisterAgentResponse confirms agent registration
type RegisterAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ClusterId     string                 `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterAgentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterAgentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterAgentResponse) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

// HeartbeatRequest contains agent health status
type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// HeartbeatResponse acknowledges heartbeat
type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// BatchSBOMFindingResponse is returned after receiving batch SBOM findings
type BatchSBOMFindingResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ReceivedCount  int32                  `protobuf:"varint,3,opt,name=received_count,json=receivedCount,proto3" json:"received_count,omitempty"`
	ProcessedCount int32                  `protobuf:"varint,4,opt,name=processed_count,json=processedCount,proto3" json:"processed_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchSBOMFindingResponse) Reset() {
	*x = BatchSBOMFindingResponse{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchSBOMFindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchSBOMFindingResponse) ProtoMessage() {}

func (x *BatchSBOMFindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchSBOMFindingResponse.ProtoReflect.Descriptor instead.
func (*BatchSBOMFindingResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *BatchSBOMFindingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BatchSBOMFindingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BatchSBOMFindingResponse) GetReceivedCount() int32 {
	if x != nil {
		return x.ReceivedCount
	}
	return 0
}

func (x *BatchSBOMFindingResponse) GetProcessedCount() int32 {
	if x != nil {
		return x.ProcessedCount
	}
	return 0
}

// CombinedFinding combines SBOM and CVE data
type CombinedFinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sbom          *SBOMFinding           `protobuf:"bytes,1,opt,name=sbom,proto3" json:"sbom,omitempty"`
	Cve           *CVEFinding            `protobuf:"bytes,2,opt,name=cve,proto3" json:"cve,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombinedFinding) Reset() {
	*x = CombinedFinding{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombinedFinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombinedFinding) ProtoMessage() {}

func (x *CombinedFinding) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombinedFinding.ProtoReflect.Descriptor instead.
func (*CombinedFinding) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *CombinedFinding) GetSbom() *SBOMFinding {
	if x != nil {
		return x.Sbom
	}
	return nil
}

func (x *CombinedFinding) GetCve() *CVEFinding {
	if x != nil {
		return x.Cve
	}
	return nil
}

// CombinedFindingResponse is returned after receiving combined findings
type CombinedFindingResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SbomId          string                 `protobuf:"bytes,3,opt,name=sbom_id,json=sbomId,proto3" json:"sbom_id,omitempty"`
	InsightsCreated string                 `protobuf:"bytes,4,opt,name=insights_created,json=insightsCreated,proto3" json:"insights_created,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CombinedFindingResponse) Reset() {
	*x = CombinedFindingResponse{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombinedFindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombinedFindingResponse) ProtoMessage() {}

func (x *CombinedFindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombinedFindingResponse.ProtoReflect.Descriptor instead.
func (*CombinedFindingResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *CombinedFindingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CombinedFindingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CombinedFindingResponse) GetSbomId() string {
	if x != nil {
		return x.SbomId
	}
	return ""
}

func (x *CombinedFindingResponse) GetInsightsCreated() string {
	if x != nil {
		return x.InsightsCreated
	}
	return ""
}

// PingRequest for health check (agent_id/node_name optional; when set, Core updates last_seen_at)
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *PingRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *PingRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

// PingResponse for health check
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

func (x *PingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type StreamEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"` // JSON-encoded AgentMessage (Agent→Core) or CoreMessage (Core→Agent)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEnvelope) Reset() {
	*x = StreamEnvelope{}
	mi := &file_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEnvelope) ProtoMessage() {}

func (x *StreamEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEnvelope.ProtoReflect.Descriptor instead.
func (*StreamEnvelope) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{9}
}

func (x *StreamEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x10fortuna.agent.v1\x1a\n" +
	"sbom.proto\x1a\tcve.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc7\x01\n" +
	"\x14RegisterAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1b\n" +
	"\tnode_name\x18\x03 \x01(\tR\bnodeName\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x06 \x01(\tR\tclusterId\"j\n" +
	"\x15RegisterAgentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x03 \x01(\tR\tclusterId\"\x7f\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"G\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9e\x01\n" +
	"\x18BatchSBOMFindingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0ereceived_count\x18\x03 \x01(\x05R\rreceivedCount\x12'\n" +
	"\x0fprocessed_count\x18\x04 \x01(\x05R\x0eprocessedCount\"t\n" +
	"\x0fCombinedFinding\x121\n" +
	"\x04sbom\x18\x01 \x01(\v2\x1d.fortuna.agent.v1.SBOMFindingR\x04sbom\x12.\n" +
	"\x03cve\x18\x02 \x01(\v2\x1c.fortuna.agent.v1.CVEFindingR\x03cve\"\x91\x01\n" +
	"\x17CombinedFindingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\asbom_id\x18\x03 \x01(\tR\x06sbomId\x12)\n" +
	"\x10insights_created\x18\x04 \x01(\tR\x0finsightsCreated\"E\n" +
	"\vPingRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\"@\n" +
	"\fPingResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"*\n" +
	"\x0eStreamEnvelope\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload2\x87\x05\n" +
	"\fAgentService\x12`\n" +
	"\rRegisterAgent\x12&.fortuna.agent.v1.RegisterAgentRequest\x1a'.fortuna.agent.v1.RegisterAgentResponse\x12T\n" +
	"\tHeartbeat\x12\".fortuna.agent.v1.HeartbeatRequest\x1a#.fortuna.agent.v1.HeartbeatResponse\x12W\n" +
	"\x0fSendSBOMFinding\x12\x1d.fortuna.agent.v1.SBOMFinding\x1a%.fortuna.agent.v1.SBOMFindingResponse\x12d\n" +
	"\x15BatchSendSBOMFindings\x12\x1d.fortuna.agent.v1.SBOMFinding\x1a*.fortuna.agent.v1.BatchSBOMFindingResponse(\x01\x12T\n" +
	"\x0eSendCVEFinding\x12\x1c.fortuna.agent.v1.CVEFinding\x1a$.fortuna.agent.v1.CVEFindingResponse\x12c\n" +
	"\x13SendCombinedFinding\x12!.fortuna.agent.v1.CombinedFinding\x1a).fortuna.agent.v1.CombinedFindingResponse\x12E\n" +
	"\x04Ping\x12\x1d.fortuna.agent.v1.PingRequest\x1a\x1e.fortuna.agent.v1.PingResponse2g\n" +
	"\x13ControlPlaneService\x12P\n" +
	"\x06Stream\x12 .fortuna.agent.v1.StreamEnvelope\x1a .fortuna.agent.v1.StreamEnvelope(\x010\x01B$Z\"github.com/fortuna/api/proto/agentb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_service_proto_goTypes = []any{
	(*RegisterAgentRequest)(nil),     // 0: fortuna.agent.v1.RegisterAgentRequest
	(*RegisterAgentResponse)(nil),    // 1: fortuna.agent.v1.RegisterAgentResponse
	(*HeartbeatRequest)(nil),         // 2: fortuna.agent.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),        // 3: fortuna.agent.v1.HeartbeatResponse
	(*BatchSBOMFindingResponse)(nil), // 4: fortuna.agent.v1.BatchSBOMFindingResponse
	(*CombinedFinding)(nil),          // 5: fortuna.agent.v1.CombinedFinding
	(*CombinedFindingResponse)(nil),  // 6: fortuna.agent.v1.CombinedFindingResponse
	(*PingRequest)(nil),              // 7: fortuna.agent.v1.PingRequest
	(*PingResponse)(nil),             // 8: fortuna.agent.v1.PingResponse
	(*StreamEnvelope)(nil),           // 9: fortuna.agent.v1.StreamEnvelope
	(*timestamppb.Timestamp)(nil),    // 10: google.protobuf.Timestamp
	(*SBOMFinding)(nil),              // 11: fortuna.agent.v1.SBOMFinding
	(*CVEFinding)(nil),               // 12: fortuna.agent.v1.CVEFinding
	(*SBOMFindingResponse)(nil),      // 13: fortuna.agent.v1.SBOMFindingResponse
	(*CVEFindingResponse)(nil),       // 14: fortuna.agent.v1.CVEFindingResponse
}
var file_service_proto_depIdxs = []int32{
	10, // 0: fortuna.agent.v1.HeartbeatRequest.timestamp:type_name -> google.protobuf.Timestamp
	11, // 1: fortuna.agent.v1.CombinedFinding.sbom:type_name -> fortuna.agent.v1.SBOMFinding
	12, // 2: fortuna.agent.v1.CombinedFinding.cve:type_name -> fortuna.agent.v1.CVEFinding
	0,  // 3: fortuna.agent.v1.AgentService.RegisterAgent:input_type -> fortuna.agent.v1.RegisterAgentRequest
	2,  // 4: fortuna.agent.v1.AgentService.Heartbeat:input_type -> fortuna.agent.v1.HeartbeatRequest
	11, // 5: fortuna.agent.v1.AgentService.SendSBOMFinding:input_type -> fortuna.agent.v1.SBOMFinding
	11, // 6: fortuna.agent.v1.AgentService.BatchSendSBOMFindings:input_type -> fortuna.agent.v1.SBOMFinding
	12, // 7: fortuna.agent.v1.AgentService.SendCVEFinding:input_type -> fortuna.agent.v1.CVEFinding
	5,  // 8: fortuna.agent.v1.AgentService.SendCombinedFinding:input_type -> fortuna.agent.v1.CombinedFinding
	7,  // 9: fortuna.agent.v1.AgentService.Ping:input_type -> fortuna.agent.v1.PingRequest
	9,  // 10: fortuna.agent.v1.ControlPlaneService.Stream:input_type -> fortuna.agent.v1.StreamEnvelope
	1,  // 11: fortuna.agent.v1.AgentService.RegisterAgent:output_type -> fortuna.agent.v1.RegisterAgentResponse
	3,  // 12: fortuna.agent.v1.AgentService.Heartbeat:output_type -> fortuna.agent.v1.HeartbeatResponse
	13, // 13: fortuna.agent.v1.AgentService.SendSBOMFinding:output_type -> fortuna.agent.v1.SBOMFindingResponse
	4,  // 14: fortuna.agent.v1.AgentService.BatchSendSBOMFindings:output_type -> fortuna.agent.v1.BatchSBOMFindingResponse
	14, // 15: fortuna.agent.v1.AgentService.SendCVEFinding:output_type -> fortuna.agent.v1.CVEFindingResponse
	6,  // 16: fortuna.agent.v1.AgentService.SendCombinedFinding:output_type -> fortuna.agent.v1.CombinedFindingResponse
	8,  // 17: fortuna.agent.v1.AgentService.Ping:output_type -> fortuna.agent.v1.PingResponse
	9,  // 18: fortuna.agent.v1.ControlPlaneService.Stream:output_type -> fortuna.agent.v1.StreamEnvelope
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_sbom_proto_init()
	file_cve_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
