#!/bin/bash
# Browser-based Dashboard Test Guide

echo "=========================================="
echo "Dashboard Browser Testing Guide"
echo "=========================================="
echo ""

DASHBOARD_URL="http://localhost:3000"
API_URL="http://localhost:8080"

echo "🌐 Access Dashboard:"
echo "  URL: $DASHBOARD_URL"
echo ""
echo "📋 Test Checklist:"
echo ""
echo "1. ✅ Dashboard Loads"
echo "   - Open $DASHBOARD_URL"
echo "   - Verify page loads without errors"
echo "   - Check browser console for errors"
echo ""
echo "2. ✅ Login (if auth enabled)"
echo "   - Username: admin"
echo "   - Password: admin123"
echo "   - Verify redirect to dashboard"
echo ""
echo "3. ✅ Dashboard Screen"
echo "   - Verify stat cards display"
echo "   - Check insights summary"
echo "   - Verify system health indicators"
echo "   - Compare with API data:"
echo "     curl $API_URL/api/v1/insights/summary"
echo ""
echo "4. ✅ Clusters Screen"
echo "   - Navigate to Clusters"
echo "   - Verify cluster list displays"
echo "   - Check status badges"
echo "   - Compare with API:"
echo "     curl $API_URL/api/v1/clusters"
echo ""
echo "5. ✅ Insights Screen"
echo "   - Navigate to Insights"
echo "   - Verify insights list"
echo "   - Test severity filters"
echo "   - Test search functionality"
echo "   - Compare with API:"
echo "     curl $API_URL/api/v1/insights?pageSize=5"
echo ""
echo "6. ✅ Resources Screen"
echo "   - Navigate to Resources"
echo "   - Test tabbed interface"
echo "   - Verify tabs switch correctly"
echo ""
echo "7. ✅ Navigation"
echo "   - Test all sidebar links"
echo "   - Verify active state highlighting"
echo "   - Check URL changes"
echo ""
echo "8. ✅ Data Accuracy"
echo "   - Compare dashboard data with API"
echo "   - Verify counts match"
echo "   - Check insight details match"
echo ""
echo "=========================================="
echo "API Test Commands"
echo "=========================================="
echo ""
echo "# Get Insights Summary"
echo "curl $API_URL/api/v1/insights/summary"
echo ""
echo "# Get Clusters"
echo "curl $API_URL/api/v1/clusters"
echo ""
echo "# Get Insights"
echo "curl $API_URL/api/v1/insights?pageSize=5"
echo ""
echo "# Get Critical Insights"
echo "curl $API_URL/api/v1/insights?severity=critical&pageSize=5"
echo ""
echo "=========================================="
echo "Database Comparison"
echo "=========================================="
echo ""
echo "# Get database counts"
echo "kubectl exec -n ksam <postgres-pod> -- psql -U postgres -d ksam -c \"SELECT COUNT(*) FROM insights;\""
echo ""

