// Package securityaudit provides append-only governance audit writes.
package securityaudit

// Normalized action names for security_activity_logs (prefix: subsystem.entity.verb).
const (
	ActionFindingsAcknowledge         = "findings.status.acknowledge"
	ActionFindingsResolve             = "findings.status.resolve"
	ActionFindingsDismiss             = "findings.status.dismiss"
	ActionFindingsPatch               = "findings.status.patch"
	ActionFindingsAssign              = "findings.assignee.set"
	ActionFindingsBulk                = "findings.bulk"
	ActionFindingsExceptionCreate     = "findings.exception.create"
	ActionFindingsExceptionDelete     = "findings.exception.delete"
	ActionInventoryServiceAccountBulk = "inventory.serviceaccount.bulk"
	ActionMalwareDBUpload             = "malware.db.upload"
	ActionAuthzDeny                   = "authz.deny"
	ActionSessionRevoke               = "session.revoke"
	ActionSessionsRevokeAll           = "sessions.revoke_all"
	ActionUserRBACChange              = "user.rbac.change"
	ActionAuditTamperDenied           = "audit.store.mutation_denied"
	ActionInvestigationsCaseCreate    = "investigations.case.create"
	ActionInvestigationsCaseUpdate    = "investigations.case.update"
	ActionInvestigationsCaseDelete    = "investigations.case.delete"
	ActionAuthPasswordChange          = "auth.password.change"
	ActionFindingsDelete              = "findings.delete"
	ActionPolicyRuleCreate            = "policy.rule.create"
	ActionPolicyRuleUpdate            = "policy.rule.update"
	ActionPolicyRuleDelete            = "policy.rule.delete"
	ActionPolicyTemplateCreate        = "policy.template.create"
	ActionPolicyTemplateUpdate        = "policy.template.update"
	ActionPolicyTemplateDelete        = "policy.template.delete"
	ActionPolicyInstanceCreate        = "policy.instance.create"
	ActionPolicyInstanceUpdate        = "policy.instance.update"
	ActionPolicyInstanceDelete        = "policy.instance.delete"
	ActionRiskRuleCreate              = "risk.rule.create"
	ActionRiskRuleUpdate              = "risk.rule.update"
	ActionRiskRuleDelete              = "risk.rule.delete"
	ActionRiskRuleImport              = "risk.rule.import"
	ActionRiskRuleExport              = "risk.rule.export"
)
